#!/bin/bash

export TELEGRAM_TOKEN=""
export HUBOT_GOOGLE_CSE_KEY=""
export HUBOT_GOOGLE_CSE_ID=""
export HUBOT_GOOGLE_IMAGES_HEAR="yes"
export HUBOT_LOG_LEVEL="debug"

docker run \
  -e "TELEGRAM_TOKEN=$TELEGRAM_TOKEN" \
  -e "HUBOT_GOOGLE_CSE_KEY=$HUBOT_GOOGLE_CSE_KEY" \
  -e "HUBOT_GOOGLE_CSE_ID=$HUBOT_GOOGLE_CSE_ID" \
  -e "HUBOT_LOG_LEVEL=$HUBOT_LOG_LEVEL" \
  hubot
